export const Auth = {
	EmailChanged: 'EmailChanged',
	PasswordChanged: 'PasswordChanged',
	ConfirmPasswordChanged: 'ConfirmPasswordChanged',
	PasswordNotMatch: 'PasswordNotMatch',
	SignIn: 'SignIn',
	SignInSuccess: 'SignInSuccess',
	SignInFail: 'SignInFail',
	BeginSignUp: 'BeginSignUp',
	SignUp: 'SignUp',
	SignUpSuccess: 'SignUpSuccess',
	SignUpFail: 'SignUpFail',
	UpdateAuthState: 'UpdateAuthState',
	SignOutSuccess: 'SignOutSuccess',
	SignOutFail: 'SignOutFail',
};

export const Event = {
	GetNameSuccess: 'GetNameSuccess',
	GetMyEventListSuccess: 'GetMyEventListSuccess',
	UpdateCurrentEvent: 'UpdateCurrentEvent',
	ResetCurrentEvent: 'ResetCurrentEvent',
	GetEventDetailSuccess: 'GetEventDetailSuccess',
	GetEventListSuccess: 'GetEventListSuccess',
	RegisterEventSuccess: 'RegisterEventSuccess',
	RegisterEventFail: 'RegisterEventFail',
	UnregisterEventSuccess: 'UnregisterEventSuccess',
	UnregisterEventFail: 'UnregisterEventFail',
	SelectUser: 'SelectUser',
	DeselectUser: 'DeselectUser',
	ResetActionMsg: 'ResetActionMsg',
	SetProfile: 'SetProfile',
	ResetProfile: 'ResetProfile',
	ExitProfilePage: 'ExitProfilePage',
	SaveProfileSuccess: 'SaveProfileSuccess',
	SaveProfileFail: 'SaveProfileFail',
	EditProfile: 'EditProfile',
	ResetIsEditingProfile: 'ResetIsEditingProfile'
};
